//! Receives the client's video with MediaMTX, which we run as a child
//! process. The client publishes to the `live` path over SRT (or RTMP) with
//! the ingest key; relays read it back over local RTMP.

use std::{path::PathBuf, process::Stdio, sync::Arc, time::Duration};

use anyhow::{Context, Result};
use tokio::{process::Command, sync::watch};

use crate::config::Config;

pub const PATH: &str = "live";
const USER: &str = "parallax";

pub struct Ingest {
    config: Arc<Config>,
    key: String,
    ready: watch::Sender<bool>,
}

impl Ingest {
    pub fn new(config: Arc<Config>, key: String) -> Arc<Ingest> {
        Arc::new(Ingest { config, key, ready: watch::channel(false).0 })
    }

    /// True while the client is sending video.
    pub fn ready(&self) -> watch::Receiver<bool> {
        self.ready.subscribe()
    }

    pub fn srt_url(&self, host: &str) -> String {
        format!("srt://{host}:{}?streamid=publish:{PATH}:{USER}:{}", self.config.srt_port, self.key)
    }

    pub fn rtmp_url(&self, host: &str) -> String {
        format!("rtmp://{host}:{}/{PATH}?user={USER}&pass={}", self.config.rtmp_port, self.key)
    }

    /// Where relays read the stream (localhost needs no credentials).
    pub fn local_read_url(&self) -> String {
        format!("rtmp://127.0.0.1:{}/{PATH}", self.config.rtmp_port)
    }

    /// Runs MediaMTX and tracks whether video is arriving. Never returns.
    pub async fn run(self: Arc<Self>) {
        let this = self.clone();
        tokio::spawn(async move { this.poll_ready().await });
        let mut backoff = Duration::from_secs(1);
        loop {
            match self.run_mediamtx().await {
                Ok(status) => tracing::error!("MediaMTX exited ({status}); restarting"),
                Err(e) => tracing::error!("couldn't run MediaMTX: {e:#}"),
            }
            tokio::time::sleep(backoff).await;
            backoff = (backoff * 2).min(Duration::from_secs(30));
        }
    }

    async fn run_mediamtx(&self) -> Result<std::process::ExitStatus> {
        let path = self.write_config()?;
        let mut child = Command::new(&self.config.mediamtx_bin)
            .arg(&path)
            // Anything MediaMTX writes (e.g. generated certificates) stays in the data dir.
            .current_dir(&self.config.data_dir)
            .stdin(Stdio::null())
            .kill_on_drop(true)
            .spawn()
            .with_context(|| format!("starting {} (install it, or set PARALLAX_MEDIAMTX)", self.config.mediamtx_bin))?;
        tracing::info!(
            "ingest listening: SRT on :{}, RTMP on :{}",
            self.config.srt_port,
            self.config.rtmp_port
        );
        Ok(child.wait().await?)
    }

    fn write_config(&self) -> Result<PathBuf> {
        let c = &self.config;
        // Only SRT and RTMP; publishing needs the ingest key, and only
        // localhost may read or use the API. SRT binds IPv4 explicitly: on
        // macOS MediaMTX's `:port` SRT socket doesn't accept IPv4.
        let yaml = format!(
            r#"# Generated by parallax-server on each start; edits are overwritten.
logLevel: info
api: yes
apiAddress: 127.0.0.1:{api}
rtsp: no
hls: no
webrtc: no
moq: no
playback: no
metrics: no
pprof: no
rtmp: yes
rtmpAddress: :{rtmp}
srt: yes
srtAddress: 0.0.0.0:{srt}
authMethod: internal
authInternalUsers:
  - user: {USER}
    pass: "{key}"
    ips: []
    permissions:
      - action: publish
        path: {PATH}
  - user: any
    pass:
    ips: ["127.0.0.1", "::1"]
    permissions:
      - action: read
      - action: api
paths:
  {PATH}: {{}}
"#,
            api = c.mediamtx_api_port,
            rtmp = c.rtmp_port,
            srt = c.srt_port,
            key = self.key,
        );
        let path = c.data_dir.join("mediamtx.yml");
        std::fs::write(&path, yaml).with_context(|| format!("writing {}", path.display()))?;
        Ok(path)
    }

    async fn poll_ready(&self) {
        #[derive(serde::Deserialize)]
        struct PathInfo {
            ready: bool,
        }
        let url = format!("http://127.0.0.1:{}/v3/paths/get/{PATH}", self.config.mediamtx_api_port);
        let http = reqwest::Client::builder().timeout(Duration::from_secs(2)).build().expect("HTTP client");
        loop {
            let ready = match http.get(&url).send().await {
                Ok(r) if r.status().is_success() => r.json::<PathInfo>().await.map(|p| p.ready).unwrap_or(false),
                _ => false,
            };
            self.ready.send_if_modified(|current| {
                let changed = *current != ready;
                *current = ready;
                if changed {
                    tracing::info!("ingest {}", if ready { "started" } else { "stopped" });
                }
                changed
            });
            tokio::time::sleep(Duration::from_secs(1)).await;
        }
    }
}
